---
title: "Returns to Housing, Equity and the Rate of Profit"
author: "Alper Duman"
---

## Returns

In  a capitalist economy the fundamental asset is supposed to be productive (ie. machinery and equipment, software/hardware) capital. However, the observed stocks of assets tell a different story. Productive capital is just less than one quarter of total wealth in the advanced countries, and probably less so in the developing countries.

A potential, though a partial, explanation is the lifetime of the productive capital being a lot less than the dwellings and other assets.



The biggest asset item is housing (real estate).
We compare the returns on real estate with the returns on equity and the rate of profit.

Both the real estate and the equity have two components of returns. 
1. Capital gains
2. Yields (rent in the case of real estate and dividend in the case of equity)

The capitalist rate of profit is only one-dimensional. Simply, it is a measure of the return on the commited productive capital.

Classical economists would be very interested in the interrelations of these returns. 
What does explain the capital gains in real estate?
Can the returns to equity be much less than the returns to real estate?
What should be the rate of profit in the long-run?


## Observations