project:
  type: website
  output-dir: docs

website:
  title: "Political Economy"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - MyBlog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



